### PR TITLE
Fix same params detection (re-merge after split of PR#59)

### PR DESCRIPTION
**Pull request by jimklimov**
@basil : To facilitate eventual merge of the fixes done in PR #59 into PRs #75, #76 and #77 this branch replays those three PRs with proper merge conflict resolution to achieve the same codebase state as in PR #59 at this time, both synced with upstream/master as of today.

### CODE REVIEW

**Comment by mmh891113** [comment]
I'm confused why this paramsToUseForLimit variable was splited by different char at line 228 and line 101 in file ThrottleJobProperty.java

when this PR will be merged???

**Comment by jimklimov** [comment]
I wonder the same... @basil? Any blockers for this and related PRs (#77, #76), or just collecting dust?

**Comment by basil** [comment]
Thanks for the reminder, I’ll try to process this in the next week or so.

**Comment by jimklimov** [comment]
Followed up by #103 and #104, released in 2.1.

**Pull request closed without merging**
