### PR TITLE
Add support for limiting job concurrency based on one or more build parameters (replaces pull request #9)

### PR DESCRIPTION
**Pull request by jmozmoz**
Latest version of pull request for  add support for limiting job concurrency based on one or more build parameters #9 including merges of upstream changes (not included in original pull request).

### CODE REVIEW

**Comment by jmozmoz** [comment]
At the moment, there a compilation errors in this branch. So it needs some more work.

**Comment by oleg-nenashev** [comment]
@jmozmoz Thanks a lot for taking the action on this pull request

**Comment by lcasey001** [comment]
+1 for this

**Comment by vmoravec** [comment]
+1 a big one. thanks.

**Comment by jmozmoz** [comment]
If I run mvn package on my computer for the master branch of this repository (7a6b581f6eadff577220cf46bed0d6371f3db63d) I get the same 5 test failures as for my branch. So I really would appreciate some help in solving these failures. Anybody has any idea what is going on?

**Comment by oleg-nenashev** [comment]
yes, somebody needs to investigate the test failures

**Comment by balldarrens** [comment]
What mvn command are you running?  Locally I have just about all tests failing:
Tests run: 15, Failures: 0, Errors: 13, Skipped: 0

Tried: mvn package/mvn install - both are the same results.  Using master branch at the following transaction:
commit 857f6dec9127ceffe3c6bd2c1b01c0c61a1e9094
Author: jmozmoz <Joachim.Herb@gmx.de>
Date:   Mon Jan 11 01:16:01 2016 +0100
    Manual merge with upstream master

**Comment by balldarrens** [comment]
So here is what I observe when I step through one of the failing testcases:

A call to this.jenkins.setNoUsageStatistics(Boolean.valueOf(true)); (HudsonTestClass.java - Line 300) results in an IOException on save (Jenkins.java - Line 2003), which in turn calls getConfigFile (Jenkins.java - Line 1839) - of which is attempting to create config.xml in the root.  The 'write' fails on this call.  Temporary file only has the XML header in it.

See: http://imgur.com/kZao2XK
http://imgur.com/kZao2XK

I don't use HudsonTestCase in my plugins, so I am not entirely familiar with this, but I would suggest that you test(s) are not in error?  I may be wrong though.  

I sure could use this enhancement.

**Comment by balldarrens** [comment]
This is fixed, with some alterations to tests and the pom.  
https://github.com/balldarrens/throttle-concurrent-builds-plugin/commit/6394b9866bf93af23d0f9515dc802b7afc551537  
I will send it to PR.

**Comment by balldarrens** [comment]
Here is the new PR: https://github.com/jenkinsci/throttle-concurrent-builds-plugin/pull/38

**Comment by balldarrens** [comment]
Replaces https://github.com/jenkinsci/throttle-concurrent-builds-plugin/pull/33

**Comment by oleg-nenashev** [comment]
#38 has been integrated, so closing this PR

**Pull request closed without merging**
