### PR TITLE
[JENKINS-31801] - Documentation Revamp + Pipeline support docs

### PR DESCRIPTION
**Pull request by oleg-nenashev**
- [x] Migrate the existing documentation from Wiki and Extend it
- [x] [JENKINS-31801](https://issues.jenkins-ci.org/browse/JENKINS-31801) - Draft the Pipeline Support section for https://github.com/jenkinsci/throttle-concurrent-builds-plugin/pull/46 
- [x] Add explicit LICENSE
- [x] Migrate Changelog from Wiki
- [x] Upgrade Parent POM to pick some Javadoc generation updates (just to justify the change in this PR, yeah)

@reviewbybees @abayer

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@abayer you may see the PR build fails due to the diamond operators after the Parent POM upgrade. Not sure why, but #46 bumps the core anyway. So I think it's safe to merge (or I can leave Parent POM bump to you)

**Comment by jglick** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@reviewbybees another review is required

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Pull request merged**
